 number = .
label = .
action = .
object_type = .
sign = .
new_line = .
text = .
text_param = .
scenario_label = .
feature_label = .
Text_line = {text} new_line .
Number_param = [sign]number["."number] .
Param = text_param|Number_param .
Object = object_type text .
Assertion = label {text} action {text} Object {text} [Param] .
Test_line = Assertion [new_line] .
Test_block = Test_line { Test_line } .  
Scenario_line = scenario_label Text_line .
Scenario = Scenario_line [Test_block] .
Feature_block = feature_label {Text_line} .
Feature = Feature_block {Scenario} .   