number = .
label = .
action = .
object_type = .
sign = .
new_line = .
text = .
text_param = .
scenario_label = .
feature_label = .
page_label = .
init_scenario_label = .
user_scenario_label = .
expect_action_label = .
expect_action_action = .
matcher = .
Text_line = {text|number} new_line .
Number_param = [sign]number["."number] .
Param = text_param|Number_param .
Object = object_type text .
Init_scenario = init_scenario_label {text} user_scenario_label text .
Expect_expression = expect_action_label {text} expect_action_action {text} Object {text} matcher [Param] .
Expect_action = label {text} action {text} Object {text} [Param] .
Test_line = Expect_action new_line .
Test_init_scenario_line = Init_scenario new_line .
Test_expect_line = Expect_expression [new_line] .
Test_block = Test_init_scenario_line Test_line { Test_line } Test_expect_line { Test_expect_line }. 
Page_line = page_label Text_line . 
Scenario_line = scenario_label Text_line .
Scenario = Scenario_line [Test_block] .
Feature_block = feature_label {Text_line} .
Feature = Feature_block Page_line {Scenario} .   